### ISSUE TITLE
Add Hover effect on buttons.

### ISSUE THREAD

**Issue by benwmx** [aliabbani/Portfolio#10]
# The project is actually really good 💯 💥 
hi Ali you have really done a great job but we think as a group reviewing your code you can still improve your project though on some aspects like : 
## add ⬆️ 

* a hover effect to the buttons.
* active effect to the buttons.
*  the navbar in the mobile version should be fixed.
* add a background image in the footer as the template.

**Comment by aliabbani** [comment]
Thank you for all these suggestions, I worked on all of them.
