### ISSUE TITLE
Bug Fix

### ISSUE THREAD

**Issue by Kalunge** [aliabbani/Portfolio#16]
Hey Ali! Your project looks good, however, there is a bug which needs fixing,

- in [this line](https://github.com/aliabbani/Portfolio/blob/bug-fix/index.js#L17)  and [line 19](https://github.com/aliabbani/Portfolio/blob/bug-fix/index.js#L19) Take away the parenthesis as you do not need to call the function. you already called it at its declaration

**Comment by aliabbani** [comment]
Thank you for all these suggestions, I worked on all of them.
